files:
  include: '**/*.s+(a|c)ss'
  ignore: 'node_modules/**'

# Rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
# 0 = off
# 1 = warning
# 2 = error
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks:
    - 1
    -
      allow-single-line-rulesets: false
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  id-name-format: 0
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format:
    - 1
    -
      convention: camelcase

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 0
  brace-style: 1
  clean-import-paths: 1
  empty-args: 0
  hex-length: 0
  hex-notation: 0
  indentation:
    - 1
    -
      size: 2
  leading-zero: 0
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 0
  property-sort-order:
    - 0
    -
      order:
        # Display
        - display
        - justify-content
        - align-items
        # Position
        - position
        - z-index
        # Size
        - min-width
        - max-width
        - width
        - min-height
        - max-heignt
        - height
        - margin
        - padding
        # Background
        - background
        - background-color
        # Text
        - font-family
        - font-size
        - line-height
        - color
        # Interaction
        - cursor
        # Animation
        - transition
        # Other
  pseudo-element: 0
  quotes: 1
  shorthand-values: 0
  url-quotes: 1
  variable-for-property: 0
  zero-unit: 0

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
